#!/bin/bash
# 🛡️ OpenClaw Skills Final Sanitization Script
# Total non-compliant skills to remove: 342

rm -rf "ai-and-llms/percept-ambient-jarvis563" # Reason: Invalid YAML header
rm -rf "ai-and-llms/modelwar-pj4533" # Reason: Invalid YAML header
rm -rf "ai-and-llms/expanso-log-sanitize" # Reason: Invalid YAML header
rm -rf "ai-and-llms/expanso-log-sanitize-aronchick" # Reason: Invalid YAML header
rm -rf "ai-and-llms/build-session-stevenartzt" # Reason: Invalid YAML header
rm -rf "ai-and-llms/social-media-extractor" # Reason: Invalid YAML header
rm -rf "ai-and-llms/percept-ambient" # Reason: Invalid YAML header
rm -rf "ai-and-llms/build-session" # Reason: Invalid YAML header
rm -rf "ai-and-llms/social-media-extractor-g4dr" # Reason: Invalid YAML header
rm -rf "ai-and-llms/modelwar" # Reason: Invalid YAML header
rm -rf "browser-and-automation/personal-sleep-gekacross" # Reason: Non-English/Non-Chinese language detected
rm -rf "browser-and-automation/social-data-arrmlet" # Reason: Invalid YAML header
rm -rf "browser-and-automation/brain-search-ryandeangraves" # Reason: Invalid YAML header
rm -rf "browser-and-automation/brain-search" # Reason: Invalid YAML header
rm -rf "browser-and-automation/asr-ilyakam" # Reason: Invalid YAML header
rm -rf "browser-and-automation/yandex-tracker-cli" # Reason: Non-English/Non-Chinese language detected
rm -rf "browser-and-automation/cls-news-scraper" # Reason: Invalid YAML header
rm -rf "browser-and-automation/client-flow" # Reason: Invalid YAML header
rm -rf "browser-and-automation/get-kalshi-live-games-kanakamedalasumanth" # Reason: Invalid YAML header
rm -rf "browser-and-automation/super-browser-heldinhow" # Reason: Invalid YAML header
rm -rf "browser-and-automation/social-data" # Reason: Invalid YAML header
rm -rf "browser-and-automation/ogment-agentic-cli-asoviche" # Reason: Invalid YAML header
rm -rf "browser-and-automation/cls-news-scraper-ningjingzhiyuande" # Reason: Invalid YAML header
rm -rf "browser-and-automation/audiomind-wells1137" # Reason: Invalid YAML header
rm -rf "browser-and-automation/client-flow-ariktulcha" # Reason: Invalid YAML header
rm -rf "browser-and-automation/get-kalshi-live-games" # Reason: Invalid YAML header
rm -rf "browser-and-automation/ub2-markdown-report-generator-underbench2-gif" # Reason: Invalid YAML header
rm -rf "browser-and-automation/sovereign-roast-coach" # Reason: Invalid YAML header
rm -rf "browser-and-automation/tg-mtproto-cli-cyberash-dev" # Reason: Invalid YAML header
rm -rf "browser-and-automation/wilma-aikarjal" # Reason: Invalid YAML header
rm -rf "browser-and-automation/asr" # Reason: Invalid YAML header
rm -rf "browser-and-automation/agent-daily-planner-gpunter" # Reason: Invalid YAML header
rm -rf "browser-and-automation/audiomind" # Reason: Invalid YAML header
rm -rf "browser-and-automation/personal-goals-gekacross" # Reason: Non-English/Non-Chinese language detected
rm -rf "browser-and-automation/sovereign-roast-coach-ryudi84" # Reason: Invalid YAML header
rm -rf "browser-and-automation/meeting-notes-pro" # Reason: Invalid YAML header
rm -rf "browser-and-automation/smart-linkedin-inbox-vdybenko" # Reason: Invalid YAML header
rm -rf "browser-and-automation/ft-reader" # Reason: Invalid YAML header
rm -rf "browser-and-automation/personal-goals" # Reason: Non-English/Non-Chinese language detected
rm -rf "browser-and-automation/meeting-notes-pro-olivermonneke" # Reason: Invalid YAML header
rm -rf "browser-and-automation/ft-reader-zhouziyue233" # Reason: Invalid YAML header
rm -rf "browser-and-automation/wilma" # Reason: Invalid YAML header
rm -rf "browser-and-automation/ub2-markdown-report-generator" # Reason: Invalid YAML header
rm -rf "browser-and-automation/smart-linkedin-inbox" # Reason: Invalid YAML header
rm -rf "browser-and-automation/tg-mtproto-cli" # Reason: Invalid YAML header
rm -rf "browser-and-automation/ogment-agentic-cli" # Reason: Invalid YAML header
rm -rf "browser-and-automation/super-browser" # Reason: Invalid YAML header
rm -rf "browser-and-automation/personal-sleep" # Reason: Non-English/Non-Chinese language detected
rm -rf "browser-and-automation/agent-daily-planner" # Reason: Invalid YAML header
rm -rf "browser-and-automation/yandex-tracker-cli-bkamuz" # Reason: Non-English/Non-Chinese language detected
rm -rf "calendar-and-scheduling/relational-permission-otherpowers" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/ub2-smart-file-organizer" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/russian-uncensored" # Reason: Non-English/Non-Chinese language detected
rm -rf "calendar-and-scheduling/russian-uncensored-voronindenis5" # Reason: Non-English/Non-Chinese language detected
rm -rf "calendar-and-scheduling/relational-permission" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/calendar-scheduling" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/temporal-cortex-datetime-billylui" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/pricing-psychology-staybased" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/temporal-cortex-datetime" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/calendar-scheduling-billylui" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/ub2-smart-file-organizer-underbench2-gif" # Reason: Invalid YAML header
rm -rf "calendar-and-scheduling/pricing-psychology" # Reason: Invalid YAML header
rm -rf "cli-utilities/cmd-executor" # Reason: Invalid YAML header
rm -rf "cli-utilities/expanso-json-flatten" # Reason: Invalid YAML header
rm -rf "cli-utilities/expanso-json-flatten-aronchick" # Reason: Invalid YAML header
rm -rf "cli-utilities/client-retention-staybased" # Reason: Invalid YAML header
rm -rf "cli-utilities/text-detection-raghulpasupathi" # Reason: Invalid YAML header
rm -rf "cli-utilities/text-detection" # Reason: Invalid YAML header
rm -rf "cli-utilities/wangwu-agent-chat-wangwu-30" # Reason: Invalid YAML header
rm -rf "cli-utilities/gmail-sender" # Reason: Invalid YAML header
rm -rf "cli-utilities/nsfw-detection-raghulpasupathi" # Reason: Invalid YAML header
rm -rf "cli-utilities/nsfw-detection" # Reason: Invalid YAML header
rm -rf "cli-utilities/notes-reminders-yusaku-0426" # Reason: Non-English/Non-Chinese language detected
rm -rf "cli-utilities/my-weather" # Reason: Invalid YAML header
rm -rf "cli-utilities/advisory-council-ryandeangraves" # Reason: Invalid YAML header
rm -rf "cli-utilities/craft-cli" # Reason: Invalid YAML header
rm -rf "cli-utilities/advisory-council" # Reason: Invalid YAML header
rm -rf "cli-utilities/craft-cli-nerveband" # Reason: Invalid YAML header
rm -rf "cli-utilities/client-retention" # Reason: Invalid YAML header
rm -rf "cli-utilities/my-weather-ryansorr1" # Reason: Invalid YAML header
rm -rf "cli-utilities/expanso-json-validate" # Reason: Invalid YAML header
rm -rf "cli-utilities/gmail-sender-junkaixue" # Reason: Invalid YAML header
rm -rf "cli-utilities/notes-reminders" # Reason: Non-English/Non-Chinese language detected
rm -rf "cli-utilities/expanso-json-validate-aronchick" # Reason: Invalid YAML header
rm -rf "cli-utilities/cmd-executor-sadikjarvis" # Reason: Invalid YAML header
rm -rf "cli-utilities/wangwu-agent-chat" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/capability-awareness" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/personal-ideas-gekacross" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/percept-speaker-id" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/office-to-md-v2-lkyyyy320" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/maritime-watch" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/seedance-2-prompt-engineering-skill" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/adhd-founder-planner" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/rhandus-file-management" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/auto-test-generator-autogame-17" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/bio-reabilita-z" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/atlassian-cli" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/on-page-seo-auditor-aaron-he-zhu" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/deepseek" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/open-notebook-integration-nantes" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/macos-desktop-control-emptyopen" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/percept-speaker-id-jarvis563" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/mistro-ando818" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/active-maintenance" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/capability-awareness-pfaria32" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/glitch-skillstore" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/on-page-seo-auditor" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/rhandus-alerting-system-rhanxerox" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/people-strategy-makkzone" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/sightglass" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/adhd-founder-planner-jankutschera" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/auto-test-generator" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/mistro" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/ui-controller" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/objection-handling-staybased" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/adblock-dns" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/icp-qualifier-visualdeptcreative" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/speckit-swarm" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/socialite-guide" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/echo-agent-krishna3554" # Reason: No SKILL.md
rm -rf "coding-agents-and-ides/glitch-skillstore-chris6970barbarian-hue" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/skillstore" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/token-economy" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/echo-agent" # Reason: No SKILL.md
rm -rf "coding-agents-and-ides/task-todo" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/hybrid-md-mkassab30-ux" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/percept-voice-cmd-jarvis563" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/smart-cron" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/sovereign-content-scraper" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/rhandus-alerting-system" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/yt-transcript" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/avatar-video-messages" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/percept-voice-cmd" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/rank-tracker" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/icp-qualifier" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/atlassian-cli-peetzweg" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/sovereign-quest-master" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/empirical-paper-analysis-skill-zhouziyue233" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/outbound-prospecting" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/personal-ideas" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/deepseek-barisoezcan1905" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/office-to-md-v2" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/outbound-prospecting-strouddustinn-bot" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/rank-tracker-aaron-he-zhu" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/local-task-runner" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/mobile-app-builder" # Reason: No SKILL.md
rm -rf "coding-agents-and-ides/local-task-runner-d-wwei" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/expanso-pii-detect" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/avatar-video-messages-thewulf7" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/objection-handling" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/find-and-book-in-network-doctors-kylemorgan-commits" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/percept-listen" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/vectorguard-nano" # Reason: No SKILL.md
rm -rf "coding-agents-and-ides/cydew-jhotson" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/skill-authoring" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/rhandus-file-management-rhanxerox" # Reason: Non-English/Non-Chinese language detected
rm -rf "coding-agents-and-ides/ozel-yetenek" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/bio-reabilita-z-zbreda" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/empirical-paper-analysis-skill" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/people-strategy" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/adblock-dns-picaye" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/code-comments-user520512" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/short-video-creator" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/expanso-pii-detect-aronchick" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/2nd-brain" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/cydew" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/code-comments" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/macos-desktop-control" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/find-and-book-in-network-doctors" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/percept-listen-jarvis563" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/active-maintenance-xiaowenzhou" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/hybrid-md" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/open-notebook-integration" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/ozel-yetenek-muhammedalibalci" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/toneclone" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/mobile-app-builder-stoplossking1" # Reason: No SKILL.md
rm -rf "coding-agents-and-ides/2nd-brain-coderaven" # Reason: Invalid YAML header
rm -rf "coding-agents-and-ides/maritime-watch-apacheua" # Reason: Invalid YAML header
rm -rf "communication/disposable-email-for-agents" # Reason: Invalid YAML header
rm -rf "communication/job-execution-monitor" # Reason: Invalid YAML header
rm -rf "communication/bookameeting" # Reason: Invalid YAML header
rm -rf "communication/email-autoreply" # Reason: Invalid YAML header
rm -rf "communication/personal-friends" # Reason: Non-English/Non-Chinese language detected
rm -rf "communication/malayalam-whatsapp" # Reason: Invalid YAML header
rm -rf "communication/intercom-conversations" # Reason: Invalid YAML header
rm -rf "communication/cs-scripts" # Reason: Invalid YAML header
rm -rf "communication/key-expiry-tracker" # Reason: Invalid YAML header
rm -rf "communication/agentmanager" # Reason: Invalid YAML header
rm -rf "communication/moments-copy" # Reason: Invalid YAML header
rm -rf "communication/tpt-generate-cover" # Reason: No SKILL.md
rm -rf "communication/m365-pnp-cli" # Reason: Invalid YAML header
rm -rf "communication/self-review" # Reason: Invalid YAML header
rm -rf "data-and-analytics/ceorater" # Reason: Invalid YAML header
rm -rf "data-and-analytics/daily-report" # Reason: Invalid YAML header
rm -rf "data-and-analytics/umea-data" # Reason: Invalid YAML header
rm -rf "data-and-analytics/design-assets" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/devvit-publishing-auditor" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/file-to-markdown" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/sql-server-toolkit" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/offline-llama" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/visa-business-planner" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/intel-synthesis" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/librenms" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/nemo" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/lattice" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/mampe-industrial-core" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/thor-generator" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/agent-watcher" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/parental-controls" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/cninfo-announcement-scraper" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/sap-fico-consultant" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/gmail-tool" # Reason: Invalid YAML header
rm -rf "devops-and-cloud/valtec-tts" # Reason: Non-English/Non-Chinese language detected
rm -rf "gaming/sovereign-rpg-xp-engine" # Reason: Invalid YAML header
rm -rf "git-and-github/zai-tts" # Reason: Invalid YAML header
rm -rf "git-and-github/idrac" # Reason: Invalid YAML header
rm -rf "git-and-github/lol-drift-blooms" # Reason: Invalid YAML header
rm -rf "git-and-github/opentangl" # Reason: Invalid YAML header
rm -rf "git-and-github/commit-analyzer" # Reason: Invalid YAML header
rm -rf "git-and-github/sovereign-git-commit-analyzer" # Reason: Invalid YAML header
rm -rf "git-and-github/super-github" # Reason: Invalid YAML header
rm -rf "git-and-github/read-optimizer" # Reason: Invalid YAML header
rm -rf "git-and-github/billy-emergency-repair" # Reason: Invalid YAML header
rm -rf "health-and-fitness/recipe-finder" # Reason: Invalid YAML header
rm -rf "health-and-fitness/ub2-api-health-checker" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/quest-board" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/ub2-csv-data-analyzer" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/unsplash" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/image-detection" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/catalog" # Reason: Non-English/Non-Chinese language detected
rm -rf "image-and-video-generation/geo-blocking" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/superpower" # Reason: Invalid YAML header
rm -rf "image-and-video-generation/medical-specialty-briefs" # Reason: No SKILL.md
rm -rf "image-and-video-generation/grok-image-cli" # Reason: Invalid YAML header
rm -rf "ios-and-macos-development/envios" # Reason: Non-English/Non-Chinese language detected
rm -rf "marketing-and-sales/agenticcreed-signup-lead" # Reason: Invalid YAML header
rm -rf "marketing-and-sales/signup-lead" # Reason: Invalid YAML header
rm -rf "marketing-and-sales/reef-copywriting" # Reason: Invalid YAML header
rm -rf "marketing-and-sales/sovereign-brand-voice-writer" # Reason: Invalid YAML header
rm -rf "marketing-and-sales/social-media-lead-generation" # Reason: Read Error: 'utf-8' codec can't decode byte 0x97 in position 926: invalid start byte
rm -rf "marketing-and-sales/lead-magnets" # Reason: Invalid YAML header
rm -rf "media-and-streaming/accountcreator" # Reason: Invalid YAML header
rm -rf "notes-and-pkm/personal-love" # Reason: Non-English/Non-Chinese language detected
rm -rf "notes-and-pkm/guava-memory" # Reason: Invalid YAML header
rm -rf "notes-and-pkm/innovation-catalyst" # Reason: Invalid YAML header
rm -rf "notes-and-pkm/finance-skill" # Reason: Invalid YAML header
rm -rf "notes-and-pkm/alexandrie" # Reason: Invalid YAML header
rm -rf "notes-and-pkm/meeting-notes" # Reason: Invalid YAML header
rm -rf "notes-and-pkm/tweet-processor" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/expanso-json-to-csv" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/expanso-xml-to-json" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/mermaid" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/twitter-reader" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/book-reader" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/scam-guards-skill" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/expanso-csv-to-json" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/expanso-json-to-yaml" # Reason: Invalid YAML header
rm -rf "pdf-and-documents/expanso-json-pretty" # Reason: Invalid YAML header
rm -rf "personal-development/expanso-cve-scan" # Reason: Invalid YAML header
rm -rf "personal-development/personal-nutrition" # Reason: Non-English/Non-Chinese language detected
rm -rf "personal-development/adhd-body-doubling" # Reason: Invalid YAML header
rm -rf "personal-development/open-lesson" # Reason: Invalid YAML header
rm -rf "personal-development/joko-jobhunter" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/dji-backup" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/qfc-order" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/social-media-manager" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/envato-comment-task-to-sheet" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/reef-n8n-automation" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/neural-memory" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/evo-clone" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/todo-boss" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/subagent-dev" # Reason: Non-English/Non-Chinese language detected
rm -rf "productivity-and-tasks/dutch-translator" # Reason: Invalid YAML header
rm -rf "productivity-and-tasks/arya-reminders" # Reason: Non-English/Non-Chinese language detected
rm -rf "productivity-and-tasks/glm-autoroute" # Reason: Invalid YAML header
rm -rf "search-and-research/arxiv-cli-tools" # Reason: Invalid YAML header
rm -rf "search-and-research/voice-memo" # Reason: Non-English/Non-Chinese language detected
rm -rf "search-and-research/medical-clinicaltrials" # Reason: Invalid YAML header
rm -rf "search-and-research/mintgarden" # Reason: Invalid YAML header
rm -rf "search-and-research/farseek" # Reason: Invalid YAML header
rm -rf "search-and-research/super-research" # Reason: Invalid YAML header
rm -rf "search-and-research/owid-oc" # Reason: No SKILL.md
rm -rf "search-and-research/lead-generation" # Reason: Invalid YAML header
rm -rf "search-and-research/hk101-living-rag" # Reason: Invalid YAML header
rm -rf "search-and-research/ai-lead-generator-skill" # Reason: Invalid YAML header
rm -rf "search-and-research/serp-analysis" # Reason: Invalid YAML header
rm -rf "search-and-research/klic-nederland" # Reason: Non-English/Non-Chinese language detected
rm -rf "search-and-research/biodiversity-corridor-calculator" # Reason: Invalid YAML header
rm -rf "search-and-research/adspirer-ads-agent" # Reason: Invalid YAML header
rm -rf "security-and-passwords/age-verification" # Reason: Invalid YAML header
rm -rf "security-and-passwords/api-security" # Reason: Invalid YAML header
rm -rf "security-and-passwords/expanso-tls-inspect" # Reason: Invalid YAML header
rm -rf "security-and-passwords/test-upload2" # Reason: Invalid YAML header
rm -rf "smart-home-and-iot/glitch-homeassistant" # Reason: Invalid YAML header
rm -rf "speech-and-transcription/deepgram" # Reason: Invalid YAML header
rm -rf "speech-and-transcription/dellight-cro-revenue-ops" # Reason: Invalid YAML header
rm -rf "transportation/percept-summarize" # Reason: Invalid YAML header
rm -rf "transportation/email-tool" # Reason: Invalid YAML header
rm -rf "transportation/personal-travel" # Reason: Non-English/Non-Chinese language detected
rm -rf "transportation/brainstorming-studio" # Reason: Invalid YAML header
rm -rf "transportation/krumpklaw" # Reason: Invalid YAML header
rm -rf "transportation/al-khanjry-bus" # Reason: Invalid YAML header
rm -rf "transportation/personal-hygiene" # Reason: Non-English/Non-Chinese language detected
rm -rf "transportation/jwdiario" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/autonomous-agent-instant-message-system" # Reason: No SKILL.md
rm -rf "web-and-frontend-development/moodle-ws-skill" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/kj-parallel-agents" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/global-agent-node-with-real-time-context-streaming-mission-form-autonomous-network-status-awaiting-peers" # Reason: No SKILL.md
rm -rf "web-and-frontend-development/monk-eye-engine" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/anti-slop-design" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/rtfm-testing" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/ub2-web-research-assistant" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/skill-auto-attach" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/backlink-analyzer" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/cancorteaw-app" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/nameserver-reverse" # Reason: No SKILL.md
rm -rf "web-and-frontend-development/next-supabase-vercel-bundle" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/travel-promos-argentinas" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/personal-notes" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/gpu-cluster-monitor" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/content-engine" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/disk-usage-watcher" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/xthezealot-stealth-browser" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/claw-shell" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/autogame-tales" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/wrynai-skill" # Reason: No SKILL.md
rm -rf "web-and-frontend-development/expert-finder" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/firmenbuchat" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/shelly-brand-name-generator" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/attio-cli" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/astra-docker" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/wheel-of-fortune" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/rubicon" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/document-multiple-repository" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/webchat-voice-full-stack" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/seo-affiliate-guide" # Reason: Non-English/Non-Chinese language detected
rm -rf "web-and-frontend-development/reeflux" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/landing-page-builder" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/skill-vettr" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/google-maps-b2b-extractor" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/jobtread-api" # Reason: Invalid YAML header
rm -rf "web-and-frontend-development/vibemate" # Reason: Invalid YAML header
